version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    rebase-strategy: 'disabled'
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        patterns:
          - '*'
    labels:
      - 'type:chore'
    ignore:
      - dependency-name: 'eslint*'
        update-types: ['version-update:semver-major']
      - dependency-name: '@eslint*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript-eslint'
        update-types: ['version-update:semver-major']
    commit-message:
      prefix: 'chore(deps)'
